### PR TITLE
New verions of compiled libamtrack library to JavaScipr with and witout WebAssembly

### PR DESCRIPTION
**Pull request by marwin1991**

### CODE REVIEW

**Comment by grzanka** [comment]
Automated commit ?

**Comment by marwin1991** [comment]
Yes, create by https://github.com/libamtrack/DockerFiles/blob/commit-lib/.travis.yml

**Comment by grzanka** [comment]
Are there any libamtrack fixes/new commits included here ?

**Comment by grzanka** [comment]
screenshot from 2019-01-06 08-19-32

Does it work ?

**Comment by marwin1991** [comment]
Maybe it is not the best idea but what do you think about keeping this file both in src and /src/static/js ? To be honest I dont know how libat.js locate libat.wasm is use some [Module[locatefile](https://kripken.github.io/emscripten-site/docs/api_reference/module.html).
I dont know if it some changes in Emscripten or in WebPack or in something else. Altho we use alwayes the same version of Emscripten.

**Comment by marwin1991** [comment]
@grzanka Check now but i think everything works nice, this PR is to close, #153 is deployed at web_dev

**Comment by marwin1991** [comment]
image

The wasm file is downloaded from /src/static/js now

**Pull request closed without merging**
