### PR TITLE
initial version of ack added

### LINKED ISSUE #325: Add acknowledge to INSPIRE project in footer

### PR DESCRIPTION
**Pull request by grzanka**
Fixes #325

### CODE REVIEW

**Comment by antytyp** [comment]
I would suggest changing the font size of added line, in contrary to the rest of the text it's too small I think. Secondly, there should be no comma after "This".
ack

**Comment by grzanka** [comment]
You are right with comma - I will fix it. As for the font size - I'd keep is as small as possible. It is necessary to have this acknowledgment, but it should not distract users too much ;)

**Comment by antytyp** [comment]
It looks fine to me.

**Comment by grzanka** [comment]
> It looks fine to me.

@antytyp if looks fine, then please finish review.

**Pull request merged**
