### PR TITLE
Added display of multiple calculator outputs combined with plots

### PR DESCRIPTION
**Pull request by antytyp**

### CODE REVIEW

**Comment by grzanka** [comment]
image

@antytyp users will probably create many data series. In such case summary of results won't be visible.
Could we put all results per serie in a single line/row ? 
On the top we could have a line/row with description of parameters ("range", "fwhm" etc) and below couple of rows with numbers ?

**Comment by antytyp** [comment]
Ok, I will improve this as you suggest.

**Comment by grzanka** [comment]
In the future I'd like to use this approach to include in the table some of the input parameters.
Usually users keep most of the parameters constant, but change only few of them - in this case I've selected 3 possible values of energy. Web interface could be clever enough to figure out which input parameters has been changed (in this case only energy) and add a column with energy values.

**Comment by grzanka** [comment]
When I rename data series, the name in table is not updated.

I did renamed two series to 'a' and 'b' - plot was updated, but table - not.

image

**Comment by grzanka** [comment]
I created 3 data series, renamed them to `a,b,c`, then deleted `b`.
Middle one (b) correctly has disappeared from the plot, but the table is now inconsitent with plot:

image

**Comment by grzanka** [comment]
Let us create a single dataset, plot it, then delete it. It disappears from the plotting are, but still an entry is left in the table:

image

**Comment by grzanka** [comment]
When I repeat the same exercise (create and delete data serie) a "Result : 0" is displayed:

image

The same applies to other plots:
image

In case there are no metadata to show the area under the plot should simply be empty, without displaying any text or "Result: 0"

**Comment by grzanka** [comment]
If I create two series and delete the first one, then whole table of metadata disappears:

image

**Comment by grzanka** [comment]
After loading a page and not clicking anything still a text about metadata is displayed
image

**Comment by grzanka** [comment]
This `metadata` is especially annoying for plots where no metadata is foreseen, i.e. 
image

**Pull request merged**
